# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  hahnapplicatonprocessfebruary2021api:
    image: hahnapplicatonprocessfebruary2021api
    build:
      context: .
      dockerfile: Hahn.ApplicatonProcess.February2021.Web/Dockerfile
    ports:
      - '5000:80'
  hahn-ui:
    image: onibokun/ui-8080
    ports:
      - '8080:80'
