# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  hahnapplicatonprocessfebruary2021web:
    image: hahnapplicatonprocessfebruary2021web
    build:
      context: .
      dockerfile: Hahn.ApplicatonProcess.February2021.Web/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
